### ISSUE TITLE
JS issue while running this app

### ISSUE THREAD

**Issue by gurpreetsbz** [samsonasik/zfember#1]
Hi, We are getting issues in emberjs as given below. Could you please review and fix them so that we can use it.

`TypeError: Handlebars is undefined
Handlebars.COMPILER_REVISION === 6); 
ember-t...iler.js (line 43, col 1)

Error: Could not find module handlebars
...a)return void 0;if(u[e]={},!o[e])throw new Error("Could not find module "+e);for...
ember.min.js (line 1, col 511)

TypeError: Ember.Application is undefined
App = Ember.Application.create();
app.js (line 1, col 1)`

Thanks

**Comment by samsonasik** [comment]
this repo is demoing ember 1, I'm re-try locally and working fine. have you run : 
```javascript
bower install
```
please read the readme: https://github.com/samsonasik/zfember#installation
